In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib as mpl
import seaborn as sns

In [2]:
df=pd.read_csv("H:/Machine Learning Algorithms/Random Forest/penguins.csv")
print(df.shape)

(344, 7)


In [3]:
df.head()

species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0  Adelie  Torgersen            39.1           18.7              181.0   
1  Adelie  Torgersen            39.5           17.4              186.0   
2  Adelie  Torgersen            40.3           18.0              195.0   
3  Adelie  Torgersen             NaN            NaN                NaN   
4  Adelie  Torgersen            36.7           19.3              193.0   

   body_mass_g     sex  
0       3750.0    MALE  
1       3800.0  FEMALE  
2       3250.0  FEMALE  
3          NaN     NaN  
4       3450.0  FEMALE

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   species            344 non-null    object 
 1   island             344 non-null    object 
 2   bill_length_mm     342 non-null    float64
 3   bill_depth_mm      342 non-null    float64
 4   flipper_length_mm  342 non-null    float64
 5   body_mass_g        342 non-null    float64
 6   sex                333 non-null    object 
dtypes: float64(4), object(3)
memory usage: 18.9+ KB


In [5]:
df.isnull().sum()

species               0
island                0
bill_length_mm        2
bill_depth_mm         2
flipper_length_mm     2
body_mass_g           2
sex                  11
dtype: int64

In [6]:
df.dropna(inplace=True)

In [7]:
df.isnull().sum()

species              0
island               0
bill_length_mm       0
bill_depth_mm        0
flipper_length_mm    0
body_mass_g          0
sex                  0
dtype: int64

In [8]:
df.sex.unique()

array(['MALE', 'FEMALE'], dtype=object)

In [9]:
pd.get_dummies(df['sex']).head()

FEMALE  MALE
0       0     1
1       1     0
2       1     0
4       1     0
5       0     1

In [10]:
sex=pd.get_dummies(df['sex'],drop_first=True)
sex.head()

MALE
0     1
1     0
2     0
4     0
5     1

In [11]:
df.island.unique()

array(['Torgersen', 'Biscoe', 'Dream'], dtype=object)

In [12]:
pd.get_dummies(df['island']).head()

Biscoe  Dream  Torgersen
0       0      0          1
1       0      0          1
2       0      0          1
4       0      0          1
5       0      0          1

In [13]:
island=pd.get_dummies(df['island'],drop_first=True)
island.head()

Dream  Torgersen
0      0          1
1      0          1
2      0          1
4      0          1
5      0          1

In [15]:
new_data=pd.concat([df,island,sex],axis=1)

In [16]:
new_data.head()

species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0  Adelie  Torgersen            39.1           18.7              181.0   
1  Adelie  Torgersen            39.5           17.4              186.0   
2  Adelie  Torgersen            40.3           18.0              195.0   
4  Adelie  Torgersen            36.7           19.3              193.0   
5  Adelie  Torgersen            39.3           20.6              190.0   

   body_mass_g     sex  Dream  Torgersen  MALE  
0       3750.0    MALE      0          1     1  
1       3800.0  FEMALE      0          1     0  
2       3250.0  FEMALE      0          1     0  
4       3450.0  FEMALE      0          1     0  
5       3650.0    MALE      0          1     1

In [17]:
new_data.drop(['sex','island'],axis=1,inplace=True)

In [18]:
new_data.head()

species  bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g  \
0  Adelie            39.1           18.7              181.0       3750.0   
1  Adelie            39.5           17.4              186.0       3800.0   
2  Adelie            40.3           18.0              195.0       3250.0   
4  Adelie            36.7           19.3              193.0       3450.0   
5  Adelie            39.3           20.6              190.0       3650.0   

   Dream  Torgersen  MALE  
0      0          1     1  
1      0          1     0  
2      0          1     0  
4      0          1     0  
5      0          1     1

In [19]:
Y=new_data["species"]
Y.head()

0    Adelie
1    Adelie
2    Adelie
4    Adelie
5    Adelie
Name: species, dtype: object

In [21]:
Y.unique()

array(['Adelie', 'Chinstrap', 'Gentoo'], dtype=object)

In [22]:
Y=Y.map({'Adelie':0,'Chinstrap':1,'Gentoo':2})
Y.head()

0    0
1    0
2    0
4    0
5    0
Name: species, dtype: int64

In [28]:
Y.unique()

array([0, 1, 2], dtype=int64)

In [32]:
X=new_data.drop(["species"],axis=1)

In [33]:
X

bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g  Dream  \
0              39.1           18.7              181.0       3750.0      0   
1              39.5           17.4              186.0       3800.0      0   
2              40.3           18.0              195.0       3250.0      0   
4              36.7           19.3              193.0       3450.0      0   
5              39.3           20.6              190.0       3650.0      0   
..              ...            ...                ...          ...    ...   
338            47.2           13.7              214.0       4925.0      0   
340            46.8           14.3              215.0       4850.0      0   
341            50.4           15.7              222.0       5750.0      0   
342            45.2           14.8              212.0       5200.0      0   
343            49.9           16.1              213.0       5400.0      0   

     Torgersen  MALE  
0            1     1  
1            1     0  
2            1     0  
4            1     0  
5            1     1  
..         ...   ...  
338          0     0  
340          0     0  
341          0     1  
342          0     0  
343          0     1  

[333 rows x 7 columns]

In [34]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.25,random_state=0)

In [35]:
from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier(n_estimators=5,criterion='entropy',random_state=0)
rf.fit(X_train,Y_train)

RandomForestClassifier(criterion='entropy', n_estimators=5, random_state=0)

In [36]:
Y

0      0
1      0
2      0
4      0
5      0
      ..
338    2
340    2
341    2
342    2
343    2
Name: species, Length: 333, dtype: int64

In [38]:
y_predict=rf.predict(X_test)
y_predict


array([0, 0, 2, 0, 0, 0, 1, 2, 2, 1, 2, 0, 0, 1, 0, 0, 2, 0, 1, 0, 0, 0,
       2, 2, 2, 2, 0, 0, 0, 0, 0, 1, 0, 1, 0, 2, 1, 0, 1, 0, 2, 2, 0, 0,
       0, 0, 0, 0, 2, 0, 0, 0, 2, 2, 0, 0, 0, 0, 0, 2, 0, 1, 0, 2, 0, 0,
       2, 2, 1, 2, 2, 1, 2, 1, 0, 2, 0, 2, 0, 2, 1, 2, 2, 2], dtype=int64)

In [40]:
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score

In [41]:
print(confusion_matrix(Y_test,y_predict))

[[42  0  0]
 [ 1 13  0]
 [ 0  0 28]]


In [42]:
print(classification_report(Y_test,y_predict))

              precision    recall  f1-score   support

           0       0.98      1.00      0.99        42
           1       1.00      0.93      0.96        14
           2       1.00      1.00      1.00        28

    accuracy                           0.99        84
   macro avg       0.99      0.98      0.98        84
weighted avg       0.99      0.99      0.99        84



In [43]:
print(accuracy_score(Y_test,y_predict))

0.9880952380952381


In [69]:
from sklearn.ensemble import RandomForestClassifier
rfg=RandomForestClassifier(n_estimators=7,criterion='gini',random_state=0)
rfg.fit(X_train,Y_train)

RandomForestClassifier(n_estimators=7, random_state=0)

In [70]:
yt_predict=rfg.predict(X_test)
yt_predict

array([0, 0, 2, 0, 0, 0, 1, 2, 2, 1, 2, 0, 0, 1, 0, 0, 2, 0, 1, 0, 0, 0,
       2, 2, 2, 2, 0, 0, 0, 0, 0, 1, 0, 0, 0, 2, 1, 0, 1, 0, 2, 2, 0, 0,
       0, 0, 0, 0, 2, 0, 0, 0, 2, 2, 0, 0, 0, 0, 0, 2, 0, 1, 0, 2, 0, 0,
       2, 2, 1, 2, 2, 1, 2, 1, 0, 2, 0, 2, 0, 2, 1, 2, 2, 2], dtype=int64)

In [71]:
print(confusion_matrix(Y_test,yt_predict))

[[42  0  0]
 [ 2 12  0]
 [ 0  0 28]]
